# get http://localhost:3001/api/relationship/getRelations

# post http://localhost:3001/api/relationship/addRelations
# Content-Type: application/json

# {
#     "firstPerson":"rashid",
#     "secondPerson":"asif",
#     "relation":"brother in law",
#     "conclusion": "rashid is asif's brother in law"
# }

# post http://localhost:3001/api/relationship/addPersons
# Content-Type: application/json

# {
#     "name":"ashok"
# }

post http://localhost:3001/api/relationship/degreeOfRelation
Content-Type: application/json

{
    "peoples": [ "raju", "ashok" ]
}